baseURL = 'https://mrpaulstone.github.io'
languageCode = 'en-us'
title = 'Paul Stone . Blog / Portfolio'
theme = "ananke"

[[params.ananke_socials]]
name = "linkedin"
url = "https://www.linkedin.com/in/mrpaulstone/"

[[params.ananke_socials]]
name = "GitHub"
url = "https://github.com/mrpaulstone/"